#!/bin/bash
# MACE (Mendoza Automated CRYSTAL Engine) Example Commands
# After sourcing your shell config or activate_mace.sh

echo "MACE (Mendoza Automated CRYSTAL Engine) Example Commands"
echo "=============================="
echo ""
echo "D12 Creation:"
echo "  # Convert CIF files to D12 (run in the directory with the .cif files)"
echo "  mace convert"
echo ""
echo "  # Create D12 from an optimized structure"
echo "  mace opt2d12 material.out"
echo ""
echo "D3 Creation:"
echo "  # Create property calculations"
echo "  mace opt2d3 material.out --calc-type BAND"
echo "  mace opt2d3 material.out --calc-type DOSS"
echo "  mace opt2d3 material.out --calc-type TRANSPORT"
echo ""
echo "Job Management:"
echo "  # Run comprehensive workflow"
echo "  mace workflow --interactive"
echo ""
echo "  # Submit jobs (a file or a directory; defaults to the current directory)"
echo "  mace submit material.d12"
echo "  mace submit ."
echo ""
echo "  # Monitor calculations"
echo "  mace monitor --status"
echo "  mace monitor"
echo ""
echo "Analysis:"
echo "  # Extract properties from completed outputs"
echo "  mace analyze --extract-properties ."
echo ""
echo "Plotting:"
echo "  # Plot band structures, DOS, CIFs, and overviews"
echo "  mace plotting"
echo ""
echo "Current environment:"
echo "  MACE_HOME=$MACE_HOME"
echo "  All script directories are in PATH"
