"""The repository credits its authors, and no AI.

This is a standing rule that had no enforcement, so it drifted: a
"with AI assistance" string sat in the CIF converter's interactive banner
across several releases and was only noticed by reading the source. The same
thing happened to the README version banner - a rule kept by hand is a rule
that eventually breaks.

Scope is deliberately the TRACKED working tree. Commit messages on main were
cleaned separately and are checked by eye at review time; unpublished local
branches are out of scope.
"""
import re
import subprocess

import pytest

from conftest import REPO_ROOT

# Substrings that would be attribution, matched case-insensitively.
# Kept narrow on purpose: bare "AI" appears inside ordinary words and inside
# real data (property_extractor parses CRYSTAL's "(...)A|I(...)" spin labels).
FORBIDDEN = [
    "co-authored-by: claude",
    "anthropic",
    "claude.ai",
    "claude code",
    "with ai assistance",
    "ai-assisted",
    "ai assistance",
    "ai-generated",
    "generated by ai",
    "chatgpt",
    "copilot",
]

# Files that legitimately discuss the rule itself.
ALLOWED = {"tests/test_no_ai_attribution.py"}


def _tracked_files():
    out = subprocess.run(["git", "ls-files", "-z"], cwd=REPO_ROOT,
                         capture_output=True, text=True, timeout=120)
    if out.returncode != 0:
        pytest.skip("not a git checkout")
    return [f for f in out.stdout.split("\0") if f]


def test_no_ai_attribution_in_tracked_files():
    offenders = []
    for rel in _tracked_files():
        if rel in ALLOWED:
            continue
        path = REPO_ROOT / rel
        if not path.is_file():
            continue
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        lowered = text.lower()
        for needle in FORBIDDEN:
            if needle in lowered:
                for i, line in enumerate(text.split("\n"), 1):
                    if needle in line.lower():
                        offenders.append(f"{rel}:{i}: {line.strip()[:90]}")
    assert offenders == [], (
        "AI attribution found in tracked files:\n  " + "\n  ".join(offenders))


def test_cif_converter_banner_credits_the_author_only():
    """The specific line that drifted, pinned."""
    src = (REPO_ROOT / "Crystal_d12" / "NewCifToD12.py").read_text()
    assert "Enhanced by Marcus Djokic" in src
    assert not re.search(r"with AI assistance", src, re.I)
