"""Quick-start / --progress BAND steps must request the SeeK-path k-path.

Found during the v1.1.1 HPCC QA (2026-08-11): seekpath 2.2.1 was installed and
importable on the compute node -- MACE's own helper used it when called
("Using seekpath library: cF2 (centrosymmetric)", 6 segments
GAMMA-X-U|K-GAMMA-L-W-X) -- yet the BAND deck generated by a
`mace submit --progress full_electronic` run came out with
kpath_source=default and a 4-segment X-GAMMA-L-W-GAMMA path.

Cause: the generator only takes the SeeK-path branch when the d3 config sets
``seekpath_full``, and _get_basic_d3_config_for_quick_start never did. The
interactive planner's expert BAND config does (kpath_source seekpath_*), so the
quick paths silently produced a lower-quality path than the interactive one.
Only matters for non-cubic lattices, where the static extended-Bravais tables
are not accurate.

The flag is requested unconditionally rather than probed at plan-build time:
plans are built on a login/gateway node, D3 files are generated later on a
compute node with a different interpreter, so probing would test the wrong
machine. get_seekpath_full_kpath is import-guarded and degrades
seekpath -> literature -> static by itself.
"""
import sys

import pytest

from conftest import REPO_ROOT

sys.path.insert(0, str(REPO_ROOT))

from mace.run_mace import _get_basic_d3_config_for_quick_start  # noqa: E402


def test_band_requests_seekpath():
    cfg = _get_basic_d3_config_for_quick_start("BAND")
    assert cfg.get("seekpath_full") is True, (
        "quick-start BAND must ask for the SeeK-path path; without this flag "
        "the generator falls back to cubic-only static tables")
    # the branch that honors seekpath_full is the 'coordinates' one
    assert cfg.get("path_method") == "coordinates", cfg


def test_band_config_still_valid():
    """The added key must not break config validation."""
    sys.path.insert(0, str(REPO_ROOT / "Crystal_d3"))
    from d3_config import validate_d3_config

    ok, errors = validate_d3_config(_get_basic_d3_config_for_quick_start("BAND"))
    assert ok, errors


@pytest.mark.parametrize("calc_type", ["DOSS", "TRANSPORT", "CHARGE+POTENTIAL"])
def test_non_band_configs_untouched(calc_type):
    """seekpath applies to k-paths only — nothing else should have grown it."""
    cfg = _get_basic_d3_config_for_quick_start(calc_type)
    assert "seekpath_full" not in cfg, cfg


def test_seekpath_helper_is_import_guarded():
    """The safety net this change relies on: requesting seekpath where it is not
    installed must degrade, not raise."""
    sys.path.insert(0, str(REPO_ROOT / "Crystal_d3"))
    import d3_kpoints

    assert hasattr(d3_kpoints, "SEEKPATH_LIBRARY_AVAILABLE"), (
        "get_seekpath_full_kpath must stay guarded by an availability flag; "
        "quick-start now requests seekpath on machines that may not have it")
