"""Plan a workflow around inputs the user already generated by hand.

`mace submit --progress` is the opt-in counterpart to the rule that a manual
submission never progresses on its own: progression needs a plan, so this
module writes a real one before the decks go to SLURM.

By the time anyone runs `mace submit`, the .d12/.d3 files exist — they came
from `mace opt2d12`/`mace opt2d3`/`mace convert`. So there is no CIF
conversion step and no first-step generation here: the existing decks ARE the
starting point (`{"source": "existing_d12"}`), and the plan describes what
should follow them.

Two levels, matching what the flag was given:

``--progress TEMPLATE``
    Sequence from the named template, per-step settings from the same
    non-interactive defaults `mace workflow --quick-start` uses. Fast, and the
    follow-up steps at least come from a real plan rather than whatever the
    engine would have improvised.

``--progress interactive``
    The planner's own step-configuration prompts — the same ones
    `mace workflow --interactive` asks — so SP functionals, BAND paths, DOSS
    windows and SLURM resources are yours, not defaults.
"""
from datetime import datetime
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, List, Optional, Tuple

from mace.workflow.common.constants import WORKFLOW_TEMPLATES
from mace.utils import ui


def available_templates() -> List[str]:
    """Template names accepted by ``--progress`` (plus ``interactive``)."""
    return sorted(WORKFLOW_TEMPLATES)


# Same values `configure_queue_management` offers as its defaults, used when
# --progress names a template (that mode asks no questions).
DEFAULT_QUEUE_CONFIG = {
    "max_jobs": 950,
    "reserve_slots": 50,
    "max_submit_batch": 10,
    "max_recovery_attempts": 3,
}


def _mint_workflow_id() -> str:
    return f"workflow_{datetime.now().strftime('%Y%m%d_%H%M%S')}"


def _template_plan(planner, sequence: List[str], input_dir: Path,
                   input_files: List[Path], workflow_id: str,
                   max_jobs: int, walltime: Optional[str] = None) -> Dict[str, Any]:
    """Quick-start's plan builder, fed existing decks instead of CIFs."""
    from mace.run_mace import create_quick_workflow_plan

    args = SimpleNamespace(max_jobs=max_jobs, work_dir=str(planner.work_dir))
    plan = create_quick_workflow_plan(input_dir, input_files, "d12", sequence, args)

    # Must precede copy_and_customize_scripts — that is what bakes the resource
    # directives into workflow_scripts/*.sh.
    if walltime:
        _apply_walltime(plan["step_configurations"], walltime)

    # Creating the planner turned this directory into a workflow root, so the
    # queue manager now resolves SLURM templates out of workflow_scripts/
    # instead of the plain submitcrystal23.sh generator. Materialize them, or
    # the very first submission dies with "Submit script not found".
    planner.copy_and_customize_scripts(plan["step_configurations"], workflow_id,
                                       DEFAULT_QUEUE_CONFIG)
    plan["queue_management"] = dict(DEFAULT_QUEUE_CONFIG)
    plan["scripts_directory"] = str(planner.work_dir / "workflow_scripts")
    return plan


def _interactive_plan(planner, sequence: List[str], input_dir: Path,
                      input_files: List[Path], workflow_id: str,
                      max_jobs: int, walltime: Optional[str] = None) -> Dict[str, Any]:
    """The planner's real prompts, minus the CIF/first-step questions."""
    # has_cifs=False makes step 1 "use the existing D12 files as-is", which is
    # exactly true here — the user built them.
    step_configs = planner.configure_workflow_steps(sequence, False)
    queue_config = planner.configure_queue_management()
    # An explicit --walltime wins over whatever the prompts collected, and must
    # be applied before the scripts are written.
    if walltime:
        _apply_walltime(step_configs, walltime)
    planner.copy_and_customize_scripts(step_configs, workflow_id, queue_config)

    return {
        "created": datetime.now().isoformat(),
        "mode": "manual_progress",
        "input_type": "d12",
        "input_directory": str(input_dir),
        "input_files": {"d12": [str(f) for f in input_files], "cif": []},
        "workflow_sequence": sequence,
        "step_configurations": step_configs,
        "cif_conversion_config": None,
        "queue_management": queue_config,
        "scripts_directory": str(planner.work_dir / "workflow_scripts"),
        "execution_settings": {
            "max_concurrent_jobs": max_jobs,
            "enable_material_tracking": True,
            "auto_progression": True,
        },
    }


def _apply_walltime(step_configs: Dict[str, Any], walltime: str) -> None:
    """Force every step's SLURM walltime, in place.

    The per-type defaults are production-sized (7 days for OPT, 3 for SP). For a
    test run those sit in the queue far longer than the job needs, so allow one
    override to cover every step of the plan.
    """
    for cfg in step_configs.values():
        slurm = cfg.get("slurm_config")
        if not isinstance(slurm, dict):
            continue
        if isinstance(slurm.get("resources"), dict):
            slurm["resources"]["walltime"] = walltime
        for script in (slurm.get("scripts") or {}).values():
            if isinstance(script, dict) and isinstance(script.get("resources"), dict):
                script["resources"]["walltime"] = walltime


def build_progress_plan(work_dir: Path, db_path: str, input_files: List[Path],
                        progress: str, max_jobs: int = 200,
                        walltime: Optional[str] = None,
                        ) -> Tuple[Path, str, List[str]]:
    """Write a workflow plan covering ``input_files`` and what follows them.

    Args:
        work_dir: where ``workflow_configs/`` is written (and where the
            completion callback will look for the plan).
        db_path: materials database the submissions will be recorded in.
        input_files: the decks about to be submitted.
        progress: a template name, or ``"interactive"``.
        max_jobs: concurrent-job ceiling recorded in the plan.

    Returns:
        ``(plan_file, workflow_id, sequence)``.

    Raises:
        ValueError: unknown template name.
    """
    from mace.workflow.planner import WorkflowPlanner

    work_dir = Path(work_dir).resolve()
    interactive = progress.strip().lower() == "interactive"
    if not interactive and progress not in WORKFLOW_TEMPLATES:
        raise ValueError(
            f"Unknown workflow template '{progress}'. "
            f"Choose one of: {', '.join(available_templates())}, or 'interactive'.")

    # Constructing the planner creates workflow_configs/outputs/temp/scripts.
    # That is intended here (this run IS becoming a workflow) and is why it
    # never happens on the default `mace submit` path.
    planner = WorkflowPlanner(str(work_dir), db_path)
    workflow_id = _mint_workflow_id()
    input_dir = Path(input_files[0]).resolve().parent if input_files else work_dir

    if interactive:
        sequence = planner.plan_workflow_sequence()
        plan = _interactive_plan(planner, sequence, input_dir, input_files,
                                 workflow_id, max_jobs, walltime)
    else:
        sequence = list(WORKFLOW_TEMPLATES[progress])
        plan = _template_plan(planner, sequence, input_dir, input_files,
                              workflow_id, max_jobs, walltime)

    # Mint the id HERE and write it into the plan. Quick-start plans carry no
    # workflow_id and let the executor mint one; there is no executor in this
    # path — the submissions themselves must be stamped with the same id the
    # plan is filed under, or the completion callback cannot find the plan.
    plan["workflow_id"] = workflow_id
    plan_file = planner.save_workflow_plan(plan)
    return plan_file, workflow_id, sequence


def position_in_sequence(calc_type: str, sequence: List[str]) -> Optional[int]:
    """1-based step number of ``calc_type`` in ``sequence``, else None.

    A hand-made deck can start anywhere in the plan (submitting an SP after a
    manual OPT is the common case), so the step number recorded with each
    submission is looked up rather than assumed to be 1.
    """
    for i, step in enumerate(sequence):
        if step == calc_type:
            return i + 1
    base = calc_type.rstrip("0123456789") or calc_type
    for i, step in enumerate(sequence):
        if (step.rstrip("0123456789") or step) == base:
            return i + 1
    return None


def describe_plan(plan_file: Path, workflow_id: str, sequence: List[str]) -> None:
    """Tell the user exactly what they just opted into."""
    ui.ok(f"\nWorkflow plan created: {plan_file.name}")
    ui.info(f"  Workflow ID: {workflow_id}")
    ui.info(f"  Sequence:    {' → '.join(sequence)}")
    ui.info("  Completed steps will progress according to this plan.")
