#!/usr/bin/env python3
"""
Check Geometry Mismatch Script
===============================

Detects follow-up D12 files (generated by CRYSTALOptToD12.py) that suffer from the
primitive-coordinates-with-conventional-cell mismatch bug.

For centered lattices (C, I, F, R), CRYSTAL reports both primitive and conventional
(crystallographic) cells. The old CRYSTALOptToD12.py bug used primitive coordinates
with conventional cell parameters, producing incorrect geometries.

This script:
1. Scans the current directory for follow-up D12 files
2. Matches each to its source .out file in --old-dir
3. Detects the coordinate/cell mismatch
4. Reports and optionally organizes files into correct vs needs_regeneration folders

Usage:
    python check_geometry_mismatch.py --old-dir /path/to/old/calculations
    python check_geometry_mismatch.py --old-dir /path/to/old/calculations --organize
    python check_geometry_mismatch.py --old-dir /path/to/old/calculations --dry-run

Author: Marcus Djokic
"""

import os
import sys
import re
import glob
import shutil
import argparse
from pathlib import Path

# Add Crystal_d12 to path for imports
sys.path.insert(0, str(Path(__file__).parent))
from d12_parsers import CrystalOutputParser


def is_followup_d12(filename):
    """
    Detect if a D12 file is a follow-up generated by CRYSTALOptToD12.py.

    CRYSTALOptToD12.py generates filenames like:
      {base}_{calctype}_{functional}_optimized.d12

    Where calctype is opt, sp, or freq. The key signature is the presence of
    _opt_, _sp_, or _freq_ followed by a functional name in the filename.

    Also detects simpler patterns where just _optimized.d12 suffix is present.
    """
    base = os.path.basename(filename)
    # Primary pattern: _opt_, _sp_, _freq_ followed by functional name
    if re.search(r'_(opt|sp|freq)_[A-Za-z0-9]', base):
        return True
    # Secondary pattern: ends with _optimized.d12
    if base.endswith('_optimized.d12'):
        return True
    return False


def parse_d12_coordinates(d12_path):
    """
    Parse a D12 file to extract space group, cell parameters, and atomic coordinates.

    Returns dict with keys: spacegroup, cell_params, atoms
    Each atom is: {atom_number, x, y, z}
    """
    with open(d12_path, 'r') as f:
        lines = [l.rstrip() for l in f.readlines()]

    result = {
        "spacegroup": None,
        "cell_params": None,
        "atoms": [],
        "dimensionality": None,
    }

    i = 0
    # Skip title
    i += 1

    # Read dimensionality keyword
    if i < len(lines):
        dim_line = lines[i].strip()
        if dim_line == "CRYSTAL":
            result["dimensionality"] = "CRYSTAL"
        elif dim_line == "SLAB":
            result["dimensionality"] = "SLAB"
        elif dim_line == "POLYMER":
            result["dimensionality"] = "POLYMER"
        elif dim_line == "MOLECULE":
            result["dimensionality"] = "MOLECULE"
        i += 1

    # Read origin setting line (for CRYSTAL)
    if result["dimensionality"] == "CRYSTAL" and i < len(lines):
        i += 1  # Skip origin setting

    # Read space group
    if i < len(lines):
        try:
            result["spacegroup"] = int(lines[i].strip())
        except ValueError:
            pass
        i += 1

    # Read cell parameters
    if i < len(lines) and result["dimensionality"] in ["CRYSTAL", "SLAB", "POLYMER"]:
        result["cell_params"] = lines[i].strip()
        i += 1

    # Read number of atoms
    if i < len(lines):
        try:
            natoms = int(lines[i].strip())
        except ValueError:
            return result
        i += 1

    # Read atomic coordinates
    for _ in range(natoms):
        if i >= len(lines):
            break
        parts = lines[i].split()
        if len(parts) >= 4:
            try:
                atom = {
                    "atom_number": parts[0],
                    "x": parts[1],
                    "y": parts[2],
                    "z": parts[3],
                }
                result["atoms"].append(atom)
            except (ValueError, IndexError):
                pass
        i += 1

    return result


def coords_match(coord_set_a, coord_set_b, tolerance=1e-5):
    """
    Check if two coordinate sets match within tolerance.
    Compares unique atoms only (by atom number and position).

    Returns (matches, max_deviation)
    """
    if not coord_set_a or not coord_set_b:
        return False, float('inf')

    # Build list of (atom_number, x, y, z) for each set
    def normalize_coords(coords):
        result = []
        for c in coords:
            try:
                result.append((
                    str(int(float(c["atom_number"])) % 200),  # Strip +200 for ECP
                    float(c["x"]),
                    float(c["y"]),
                    float(c["z"]),
                ))
            except (ValueError, KeyError):
                continue
        return sorted(result, key=lambda x: (x[0], x[1], x[2], x[3]))

    set_a = normalize_coords(coord_set_a)
    set_b = normalize_coords(coord_set_b)

    if len(set_a) != len(set_b):
        return False, float('inf')

    max_dev = 0.0
    for a, b in zip(set_a, set_b):
        if a[0] != b[0]:  # Different atom types
            return False, float('inf')
        dev = max(abs(a[1] - b[1]), abs(a[2] - b[2]), abs(a[3] - b[3]))
        max_dev = max(max_dev, dev)

    return max_dev < tolerance, max_dev


def find_source_out_file(d12_name, old_dir):
    """
    Given a follow-up d12 filename, find the corresponding .out file in old_dir.

    CRYSTALOptToD12.py appends _{calctype}_{functional}_optimized to the source base name.
    The source base name itself may contain _opt, _sp, etc. as part of the original name.

    Strategy: find all positions where _(opt|sp|freq)_ occurs, try each as a split point
    from RIGHT to LEFT, and return the first one that matches an existing .out file.
    """
    base = d12_name
    if base.endswith('.d12'):
        base = base[:-4]

    # Find all positions where _(opt|sp|freq)_ occurs in the name
    # These are candidate split points where CRYSTALOptToD12 appended its suffix
    split_candidates = []
    for match in re.finditer(r'_(opt|sp|freq)_', base):
        candidate_base = base[:match.start()]
        split_candidates.append(candidate_base)

    # Also try stripping just _optimized from the end (in case suffix is simpler)
    if base.endswith('_optimized'):
        stripped = base[:-len('_optimized')]
        # Then try stripping the functional and calc type
        for match in re.finditer(r'_(opt|sp|freq)_', stripped):
            candidate_base = stripped[:match.start()]
            if candidate_base not in split_candidates:
                split_candidates.append(candidate_base)

    # Try candidates from RIGHT to LEFT (rightmost split is most likely correct,
    # since the source name may contain _opt as part of its own name)
    split_candidates.reverse()

    for source_base in split_candidates:
        if not source_base:
            continue
        out_file = os.path.join(old_dir, source_base + ".out")
        if os.path.exists(out_file):
            return out_file

    # If no exact match, try glob for partial matches (right to left)
    for source_base in split_candidates:
        if not source_base:
            continue
        candidates = glob.glob(os.path.join(old_dir, source_base + "*.out"))
        if candidates:
            return min(candidates, key=len)

    # Final fallback: try the full base name as-is
    out_file = os.path.join(old_dir, base + ".out")
    if os.path.exists(out_file):
        return out_file

    return None


def find_source_d12_file(d12_name, old_dir):
    """Find the corresponding source .d12 file in old_dir."""
    base = d12_name
    if base.endswith('.d12'):
        base = base[:-4]

    # Same right-to-left strategy as find_source_out_file
    split_candidates = []
    for match in re.finditer(r'_(opt|sp|freq)_', base):
        candidate_base = base[:match.start()]
        split_candidates.append(candidate_base)

    if base.endswith('_optimized'):
        stripped = base[:-len('_optimized')]
        for match in re.finditer(r'_(opt|sp|freq)_', stripped):
            candidate_base = stripped[:match.start()]
            if candidate_base not in split_candidates:
                split_candidates.append(candidate_base)

    split_candidates.reverse()

    for source_base in split_candidates:
        if not source_base:
            continue
        d12_file = os.path.join(old_dir, source_base + ".d12")
        if os.path.exists(d12_file):
            return d12_file

    for source_base in split_candidates:
        if not source_base:
            continue
        candidates = glob.glob(os.path.join(old_dir, source_base + "*.d12"))
        if candidates:
            return min(candidates, key=len)

    out_file = os.path.join(old_dir, base + ".d12")
    if os.path.exists(out_file):
        return out_file

    return None


def find_related_files(d12_path):
    """Find files related to this d12 (same base name, different extensions)."""
    base = d12_path.rsplit('.d12', 1)[0]
    related = []
    for ext in ['.sh', '.out', '.f9', '.f25']:
        candidate = base + ext
        if os.path.exists(candidate):
            related.append(candidate)
    # Also find SLURM output files (.o12345 pattern)
    for f in glob.glob(base + '.o*'):
        if f != d12_path:
            related.append(f)
    # Find job output files with job IDs (base-123456.o pattern)
    parent = os.path.dirname(d12_path) or '.'
    fname = os.path.basename(base)
    for f in glob.glob(os.path.join(parent, fname + '-*.o')):
        related.append(f)
    return related


def check_mismatch(d12_path, old_dir):
    """
    Check if a follow-up D12 file has the primitive/conventional coordinate mismatch.

    Returns: (status, details)
        status: "mismatch", "correct", "skipped", "error"
        details: descriptive string
    """
    d12_name = os.path.basename(d12_path)

    # Parse the follow-up d12
    d12_data = parse_d12_coordinates(d12_path)
    if not d12_data["atoms"]:
        return "error", "Could not parse D12 coordinates"

    # Find source .out file
    source_out = find_source_out_file(d12_name, old_dir)
    if not source_out:
        return "skipped", f"Source .out not found in {old_dir}"

    # Parse the output file
    try:
        parser = CrystalOutputParser(source_out)
        out_data = parser.parse()
    except Exception as e:
        return "error", f"Failed to parse output: {e}"

    # Check if this is a centered lattice (has both primitive and conventional cells)
    primitive_coords = out_data.get("coordinates", [])
    crystallographic_coords = out_data.get("crystallographic_coordinates", [])
    conventional_cell = out_data.get("conventional_cell")

    if not conventional_cell:
        # Primitive lattice - no mismatch possible
        return "correct", "Primitive lattice (no centering), coordinates are unambiguous"

    if not crystallographic_coords:
        # No crystallographic coordinates extracted - can't verify
        return "skipped", "Crystallographic coordinates not found in output"

    if not primitive_coords:
        return "skipped", "Primitive coordinates not found in output"

    # Filter to unique atoms only for comparison
    d12_unique = d12_data["atoms"]
    prim_unique = [c for c in primitive_coords if c.get("is_unique", True)]
    cryst_unique = [c for c in crystallographic_coords if c.get("is_unique", True)]

    # Compare d12 coordinates against primitive and crystallographic sets
    matches_prim, dev_prim = coords_match(d12_unique, prim_unique)
    matches_cryst, dev_cryst = coords_match(d12_unique, cryst_unique)

    if matches_cryst:
        return "correct", f"Coordinates match crystallographic cell (dev={dev_cryst:.2e})"
    elif matches_prim:
        return "mismatch", (
            f"PRIMITIVE coordinates used with CONVENTIONAL cell! "
            f"(prim_dev={dev_prim:.2e}, cryst_dev={dev_cryst:.2e})"
        )
    else:
        # Neither matches well - might be a different issue
        return "skipped", (
            f"Coordinates don't match either set well "
            f"(prim_dev={dev_prim:.2e}, cryst_dev={dev_cryst:.2e})"
        )


def organize_files(results, old_dir, dry_run=False):
    """Organize files into correct_geometry/ and needs_regeneration/ folders."""
    correct_dir = "correct_geometry"
    regen_dir = "needs_regeneration"

    if not dry_run:
        os.makedirs(correct_dir, exist_ok=True)
        os.makedirs(regen_dir, exist_ok=True)

    for d12_path, status, details in results:
        if status == "skipped" or status == "error":
            continue

        d12_name = os.path.basename(d12_path)
        related = find_related_files(d12_path)

        if status == "correct":
            target_dir = correct_dir
            action = "Move"
        elif status == "mismatch":
            target_dir = regen_dir
            action = "Move"
        else:
            continue

        # Move the d12 and related files
        all_files = [d12_path] + related
        for f in all_files:
            fname = os.path.basename(f)
            target = os.path.join(target_dir, fname)
            if dry_run:
                print(f"  [DRY-RUN] {action}: {fname} -> {target_dir}/")
            else:
                shutil.move(f, target)
                print(f"  {action}d: {fname} -> {target_dir}/")

        # For mismatched files, also copy the source .out and .d12
        if status == "mismatch":
            source_out = find_source_out_file(d12_name, old_dir)
            source_d12 = find_source_d12_file(d12_name, old_dir)

            for src in [source_out, source_d12]:
                if src and os.path.exists(src):
                    fname = os.path.basename(src)
                    target = os.path.join(regen_dir, fname)
                    if dry_run:
                        print(f"  [DRY-RUN] Copy: {fname} -> {target_dir}/")
                    else:
                        shutil.copy2(src, target)
                        print(f"  Copied: {fname} -> {target_dir}/")


def main():
    parser = argparse.ArgumentParser(
        description="Detect primitive/conventional coordinate mismatch in follow-up D12 files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Check files in current directory against old calculations
  python check_geometry_mismatch.py --old-dir /path/to/old/calculations

  # Check and organize files
  python check_geometry_mismatch.py --old-dir /path/to/old/calculations --organize

  # Dry run (show what would happen)
  python check_geometry_mismatch.py --old-dir /path/to/old/calculations --organize --dry-run

After organizing, run 'mace opt2d12' in needs_regeneration/ to regenerate the bad files.
        """
    )
    parser.add_argument(
        "--old-dir", required=True,
        help="Directory containing the original .out and .d12 files"
    )
    parser.add_argument(
        "--check-dir", default=".",
        help="Directory containing follow-up D12 files to check (default: current dir)"
    )
    parser.add_argument(
        "--organize", action="store_true",
        help="Organize files into correct_geometry/ and needs_regeneration/ folders"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would happen without making changes"
    )
    parser.add_argument(
        "--pattern", default=None,
        help="Glob pattern for D12 files (default: auto-detect follow-up files from all *.d12)"
    )
    parser.add_argument(
        "--all", action="store_true",
        help="Check ALL d12 files, not just detected follow-ups"
    )

    args = parser.parse_args()

    if not os.path.isdir(args.old_dir):
        print(f"Error: --old-dir '{args.old_dir}' is not a directory")
        sys.exit(1)

    # Find follow-up d12 files
    if args.pattern:
        # Explicit pattern: use as-is
        d12_files = sorted(glob.glob(os.path.join(args.check_dir, args.pattern)))
        if not d12_files:
            print(f"No D12 files matching '{args.pattern}' found in {args.check_dir}")
            sys.exit(0)
    else:
        # Auto-detect: scan all .d12 files and filter to follow-ups
        all_d12 = sorted(glob.glob(os.path.join(args.check_dir, "*.d12")))
        if not all_d12:
            print(f"No .d12 files found in {args.check_dir}")
            sys.exit(0)
        if args.all:
            d12_files = all_d12
        else:
            d12_files = [f for f in all_d12 if is_followup_d12(f)]
            if not d12_files:
                print(f"No follow-up D12 files detected in {args.check_dir}")
                print(f"  (looked for files with _opt_, _sp_, _freq_ patterns or _optimized.d12 suffix)")
                print(f"  Found {len(all_d12)} total .d12 files. Use --all to check all of them,")
                print(f"  or --pattern 'your_pattern.d12' to specify a custom pattern.")
                sys.exit(0)

    mode_desc = "auto-detected follow-up" if not args.pattern and not args.all else "matching"
    print(f"Checking {len(d12_files)} {mode_desc} D12 files...")
    print(f"Old calculations directory: {args.old_dir}")
    print("=" * 70)

    results = []
    counts = {"correct": 0, "mismatch": 0, "skipped": 0, "error": 0}

    for d12_path in d12_files:
        d12_name = os.path.basename(d12_path)
        status, details = check_mismatch(d12_path, args.old_dir)
        results.append((d12_path, status, details))
        counts[status] += 1

        # Status indicators
        indicators = {
            "correct": "[OK]",
            "mismatch": "[BAD]",
            "skipped": "[SKIP]",
            "error": "[ERR]",
        }
        print(f"  {indicators[status]:6s} {d12_name}")
        if status in ["mismatch", "error"]:
            print(f"         {details}")

    # Summary
    print()
    print("=" * 70)
    print("SUMMARY:")
    print(f"  Correct geometry:     {counts['correct']}")
    print(f"  Mismatched geometry:  {counts['mismatch']}")
    print(f"  Skipped:              {counts['skipped']}")
    print(f"  Errors:               {counts['error']}")
    print()

    if counts['mismatch'] == 0:
        print("All files have correct geometry!")
        return

    # Organize if requested
    if args.organize:
        print("Organizing files...")
        print("-" * 40)
        organize_files(results, args.old_dir, dry_run=args.dry_run)
        print()
        if args.dry_run:
            print("[DRY-RUN] No files were actually moved.")
        else:
            print(f"Done! Files organized into:")
            print(f"  correct_geometry/     - {counts['correct']} good calculations")
            print(f"  needs_regeneration/   - {counts['mismatch']} to redo")
            print()
            print("To regenerate the bad files:")
            print("  cd needs_regeneration/")
            print("  mace opt2d12 --directory .")
    else:
        print("Run with --organize to sort files into folders.")
        print("Run with --organize --dry-run to preview the organization.")


if __name__ == "__main__":
    main()
